services:
  db:
    image: postgres
    restart: unless-stopped
    container_name: burningstation_db
    environment:
      POSTGRES_PASSWORD: handsome
      TZ: America/Los_Angeles
    privileged: true
    volumes:
      - ./postgres-data:/var/lib/postgresql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    restart: unless-stopped
    container_name: burningstation_pgadmin
    privileged: true
    environment:
      PGADMIN_DEFAULT_EMAIL: handsome@guapos.com
      PGADMIN_DEFAULT_PASSWORD: handsome
    volumes:
      - ./servers.json:/pgadmin4/servers.json
    ports:
      - "8080:80"
    depends_on:
      - db 